import {
    Circle,
    SemiCircle,
    HorizontalLine,
    VerticalLine,
    SolidTriangle,
    Square,
    Reactange,
    CrossSign,
    Star,
    AppsIcon,
    SunSolid,
    SunSolidHorizon,
    ArrowToLeft,
    ArrowToRight,
    ArrowToDown,
    ArrowToUp,
    TripleDotsHorizontal,
    TripleDotsVertical,
    MenuIconHorizontal,
    FileIcon,
    Folder,
    Profile,
    BatteryEmpty,
    BatteryHalfEmpty,
    BatteryFull,
    Mobile,
    Laptop,
    LaptopWithText,
    Building,
    NotAllowed,
    CreditCard,
    DiceOne,
    DiceTwo,
    DiceThree,
    DiceFour,
    DiceFive,
    DiceSix,
    OpenInNewTab,
    WindowsIcon,
    PlusSign,
    MinusSign,
    MultiplySign,
    DivideSign,
    Gmail,
    Instagram,
    Focus,
    ReactIcon,
    BriefCase,
    Globe,
    Moon,
    Correct,
    Wrong,
    SearchIcon,
    ZoomInIcon,
    ZoomOutIcon,
    USB,
    Eye,
    Image,
    Lock,
    LockOpen,
    Dialpad,
    Pokemon,
    Calendar,
    SettingsSlider,
    Mouse,
    Facebook,
    List,
    Marker,
    Youtube,
    Home,
    Camera,
    Stats,
    UserAdd,
    Pause
  } from "./single-element-icons";

  import { TwitterBadge } from "./multi-element-icons/twitterBadge";

const ComponentMapData = [
  ['dice_one', {name: 'Dice One', id: 'dice_one', component: DiceOne}],
  ['dice_two', {name: 'Dice Two', id: 'dice_two', component:DiceTwo}],
  ['dice_three', {name: 'Dice Three', id: 'dice_three', component: DiceThree}],
  ['dice_four',  {name: 'Dice Four', id:'dice_four', component:DiceFour}],
  ['dice_five', {name: 'Dice Five', id: 'dice_five', component:DiceFive}],
  ['dice_six', {name: 'Dice Six', id: 'dice_six', component:DiceSix}],
  ['apps', {name: 'Apps', id:'apps', component: AppsIcon}],
  ['sun_solid', {name: 'Sun Solid', id: 'sun_solid', component:SunSolid}],
  ['sun_solid_horizon', {name: 'Sun Solid Horizon', id: 'sun_solid_horizon', component:SunSolidHorizon}],
  ['arrow_to_left', {name: 'Arrow Left', id: 'arrow_to_left', component:ArrowToLeft}],
  ['arrow_to_right', {name: 'Arrow Right', id: 'arrow_to_right', component:ArrowToRight}],
  ['arrow_to_down',  {name: 'Arrow Down', id: 'arrow_to_down', component:ArrowToDown}],
  ['arrow_to_up',  {name: 'Arrow Up', id: 'arrow_to_up', component:ArrowToUp}],
  ['file',  {name: 'File', id: 'file', component: FileIcon}],
  ['folder',  {name: 'Folder', id:'folder', component: Folder}],
  ['building',  {name: 'Building', id: 'building', component: Building}],
  ['credit_card',  {name: 'Credit Card', id: 'credit_card', component: CreditCard}],
  ['windows',  {name: 'Windows', id: 'windows', component: WindowsIcon}],
  ['solid_triangle',  {name: 'Solid Triangle', id: 'solid_triangle', component:SolidTriangle}],
  ['plus',  {name: 'Plus', id: 'plus', component: PlusSign}],
  ['minus',  {name: 'Minus', id: 'minus', component:MinusSign}],
  ['multiply',  {name: 'Multiply', id: 'multiply', component: MultiplySign}],
  ['divide',  {name: 'Divide', id: 'divide', component: DivideSign}],
  ['gmail',  {name: 'Gmail', id: 'gmail', component: Gmail}],
  ['instagram',  {name: 'Instagram', id: 'instagram', component: Instagram}],
  ['facebook',  {name: 'Facebook', id: 'facebook', component: Facebook}],
  ['globe',  {name: 'Globe', id: 'globe', component: Globe}],
  ['moon',  {name: 'Moon', id: 'moon', component: Moon}],
  ['correct',  {name: 'Correct', id:'correct', component: Correct}],
  ['wrong',  {name: 'Wrong', id: 'wrong', component: Wrong}],
  ['search',  {name: 'Search', id: 'search', component: SearchIcon}],
  ['zoom_in',  {name: 'Zoom In', id: 'zoom_in', component: ZoomInIcon}],
  ['zoom_out',  {name: 'Zoom Out', id: 'zoom_out', component: ZoomOutIcon}],
  ['usb',  {name: 'USB', id: 'usb', component: USB}],
  ['eye',  {name: 'Eye', id:'eye', component: Eye}],
  ['image',  {name: 'Image', id:'image', component: Image}],
  ['lock',  {name: 'Lock', id:'lock', component: Lock}],
  ['lock_open',  {name: 'Lock Open', id:'lock_open', component: LockOpen}],
  ['dialpad',  {name: 'Dialpad', id: 'dialpad', component: Dialpad}],
  ['pokemon',  {name: 'Pokemon', id: 'pokemon', component: Pokemon}],
  ['calendar',  {name: 'Calendar', id: 'calendar', component: Calendar}],
  ['settings_slider',  {name: 'Settings Slider', id: 'settings_slider', component: SettingsSlider}],
  ['mouse',  {name: 'Mouse', id: 'mouse', component: Mouse}],
  ['list',  {name: 'List', id:'list', component: List}],
  ['marker',  {name: 'Marker', id:'marker', component: Marker}],
  ['youtube',  {name: 'Youtube', id: 'youtube', component: Youtube}],
  ['home',  {name: 'Home', id: 'home', component: Home}],
  ['camera',  {name: 'Camera', id: 'camera', component: Camera}],
  ['twitter_badge',  {name: 'Twitter Badge', id:'twitter_badge', component: TwitterBadge}],
  ['stats',  {name: 'Stats', id:'stats', component: Stats}],
  ['pause',  {name: 'Pause', id:'pause', component: Pause}],
    // light icons
  ['battery_full',  {name: 'Battery Full', id:'battery_full', component: BatteryFull}],
  ['battery_half_empty',  {name: 'Battery Half', id: 'battery_half_empty', component:BatteryHalfEmpty}],
  ['battery_empty',  {name: 'Battery Empty', id:'battery_empty', component: BatteryEmpty}],
  ['circle',  {name: 'Circle', id:'circle', component: Circle}],
  ['semi_circle',  {name: 'Semi Circle', id: 'semi_circle', component: SemiCircle}],
  ['horizontal_line',  {name: 'Horizontal Line', id: 'horizontal_line', component:HorizontalLine}],
  ['vertical_line',  {name: 'Vertical Line', id:'vertical_line', component: VerticalLine}],
  ['square',  {name: 'Square', id:'square', component: Square}],
  ['rectangle',  {name: 'Rectangle', id:'rectangle', component: Reactange}],
  ['cross',  {name: 'Cross', id:'cross', component: CrossSign}],
  ['star',  {name: 'Star', id:'star', component: Star}],
  ['triple_dot_horizontal', {name: 'Triple Dot Horizontal', id: 'triple_dot_horizontal', component: TripleDotsHorizontal}],
  ['triple_dot_vertical',  {name: 'Triple Dot Vertical', id:'triple_dot_vertical', component: TripleDotsVertical}],
  ['menu_horizontal',  {name: 'Menu Horizontal', id:'menu_horizontal', component: MenuIconHorizontal}],
  ['prpfile',  {name: 'Profile', id:'prpfile', component: Profile}],
  ['mobile',  {name: 'Mobile', id:'mobile', component: Mobile}],
  ['laptop',  {name: 'Laptop', id:'laptop', component: Laptop}],
  ['laptop_with_text',  {name: 'Laptop With Text', id:'laptop_with_text', component: LaptopWithText}],
  ['open_in_new_tab',  {name: 'Open In New Tab', id:'open_in_new_tab', component: OpenInNewTab}],
  ['not_allowed',  {name: 'Not Allowed', id:'not_allowed', component: NotAllowed}],
  ['focus', {name: 'Focus', id: 'focus', component: Focus}],
  ['react',  {name: 'React', id:'react', component: ReactIcon}],
  ['briefcase',  {name: 'Briefcase', id:'briefcase', component: BriefCase}],
  ['userAdd',  {name: 'User Add', id:'userAdd', component: UserAdd}]
]

export const ComponentMap = new Map(ComponentMapData)