import {
    Circle,
    SemiCircle,
    HorizontalLine,
    VerticalLine,
    SolidTriangle,
    Square,
    Reactange,
    CrossSign,
    Star,
    AppsIcon,
    SunSolid,
    SunSolidHorizon,
    ArrowToLeft,
    ArrowToRight,
    ArrowToDown,
    ArrowToUp,
    TripleDotsHorizontal,
    TripleDotsVertical,
    MenuIconHorizontal,
    FileIcon,
    Folder,
    Profile,
    BatteryEmpty,
    BatteryHalfEmpty,
    BatteryFull,
    Mobile,
    Laptop,
    LaptopWithText,
    Building,
    NotAllowed,
    CreditCard,
    DiceOne,
    DiceTwo,
    DiceThree,
    DiceFour,
    DiceFive,
    DiceSix,
    OpenInNewTab,
    WindowsIcon,
    PlusSign,
    MinusSign,
    MultiplySign,
    DivideSign,
    Gmail,
    Instagram,
    Focus,
    ReactIcon,
    BriefCase,
    Globe,
    Moon,
    Correct,
    Wrong,
    SearchIcon,
    ZoomInIcon,
    ZoomOutIcon,
    USB,
    Eye,
    Image,
    Lock,
    LockOpen,
    Dialpad,
    Pokemon,
    Calendar,
    SettingsSlider,
    Mouse,
    Facebook,
    List
  } from "./icons";

export const ComponentsMap = {
    // dark icons
    dice_one: DiceOne,
    dice_two:DiceTwo,
    dice_three:DiceThree,
    dice_four:DiceFour,
    dice_five:DiceFive,
    dice_six:DiceSix,
    apps: AppsIcon,
    sun_solid:SunSolid,
    sun_solid_horizon:SunSolidHorizon,
    arrow_to_left:ArrowToLeft,
    arrow_to_right:ArrowToRight,
    arrow_to_down:ArrowToDown,
    arrow_to_up:ArrowToUp,
    file: FileIcon,
    folder: Folder,
    building: Building,
    credit_card: CreditCard,
    windows: WindowsIcon,
    solid_triangle:SolidTriangle,
    plus: PlusSign,
    minus:MinusSign,
    multiply: MultiplySign,
    divide: DivideSign,
    gmail: Gmail,
    instagram: Instagram,
    facebook: Facebook,
    globe: Globe,
    moon: Moon,
    correct: Correct,
    wrong: Wrong,
    search: SearchIcon,
    zoom_in: ZoomInIcon,
    zoom_out: ZoomOutIcon,
    usb: USB,
    eye: Eye,
    image: Image,
    lock: Lock,
    lock_open: LockOpen,
    dialpad: Dialpad,
    pokemon: Pokemon,
    calendar: Calendar,
    settings_slider: SettingsSlider,
    mouse: Mouse,
    list: List,
    // light icons
    battery_full: BatteryFull,
    battery_half_empty:BatteryHalfEmpty,
    battery_empty: BatteryEmpty,
    circle: Circle,
    semi_circle: SemiCircle,
    horizontal_line:HorizontalLine,
    vertical_line: VerticalLine,
    square: Square,
    rectangle: Reactange,
    cross: CrossSign,
    star: Star,
    triple_dot_horizontal: TripleDotsHorizontal,
    triple_dot_vertical: TripleDotsVertical,
    menu_horizontal: MenuIconHorizontal,
    prpfile: Profile,
    mobile: Mobile,
    laptop: Laptop,
    laptop_with_text: LaptopWithText,
    open_in_new_tab: OpenInNewTab,
    not_allowed: NotAllowed,
    focus: Focus,
    react: ReactIcon,
    briefcase: BriefCase
};

export const Components = [
    // dark icons
    DiceOne,
    DiceTwo,
    DiceThree,
    DiceFour,
    DiceFive,
    DiceSix,
    AppsIcon,
    SunSolid,
    SunSolidHorizon,
    ArrowToLeft,
    ArrowToRight,
    ArrowToDown,
    ArrowToUp,
    FileIcon,
    Folder,
    Building,
    CreditCard,
    WindowsIcon,
    SolidTriangle,
    PlusSign,
    MinusSign,
    MultiplySign,
    DivideSign,
    Gmail,
    Instagram,
    Facebook,
    Globe,
    Moon,
    Correct,
    Wrong,
    SearchIcon,
    ZoomInIcon,
    ZoomOutIcon,
    USB,
    Eye,
    Image,
    Lock,
    LockOpen,
    Dialpad,
    Pokemon,
    Calendar,
    SettingsSlider,
    Mouse,
    List,
    // light icons
    BatteryFull,
    BatteryHalfEmpty,
    BatteryEmpty,
    Circle,
    SemiCircle,
    HorizontalLine,
    VerticalLine,
    Square,
    Reactange,
    CrossSign,
    Star,
    TripleDotsHorizontal,
    TripleDotsVertical,
    MenuIconHorizontal,
    Profile,
    Mobile,
    Laptop,
    LaptopWithText,
    OpenInNewTab,
    NotAllowed,
    Focus,
    ReactIcon,
    BriefCase
  ];

  export const ComponentsList = {
    dice_one: 'Dice One',
    dice_two:'Dice Two',
    dice_three:'Dice Three',
    dice_four:'Dice Four',
    dice_five:'Dice Five',
    dice_six:'Dice Six',
    apps: 'Apps',
    sun_solid:'Sun Solid',
    sun_solid_horizon:'Sun Solid Horizon',
    arrow_to_left:'Arrow Left',
    arrow_to_right:'Arrow Right',
    arrow_to_down:'Arrow Down',
    arrow_to_up:'Arrow Up',
    file: 'File',
    folder: 'Folder',
    building: 'Building',
    credit_card: 'Credit Card',
    windows: 'Windows',
    solid_triangle:'Solid Triangle',
    plus: 'Plus',
    minus:'Minus',
    multiply: 'Multiply',
    divide: 'Divide',
    gmail: 'Gmail',
    instagram: 'Instagram',
    globe: 'Globe',
    moon: 'Moon',
    correct: 'Correct',
    wrong: 'Wrong',
    search: 'Search',
    zoom_in: 'Zoom In',
    zoom_out: 'Zoom Out',
    usb: 'USB',
    eye: 'Eye',
    image: 'Image',
    lock: 'Lock',
    lock_open: 'Lock Open',
    dialpad: 'Dialpad',
    pokemon: 'Pokemon',
    calendar : 'Calendar',
    settings_slider: 'Settings slider',
    mouse: 'Mouse',
    facebook: 'Facebook',
    list: 'List',
    // light icons
    battery_full: 'Battery Full',
    battery_half_empty:'Battery Half Empty',
    battery_empty: 'Battery Empty',
    circle: 'Circle',
    semi_circle: 'Semi Circle',
    horizontal_line:'Horizontal Line',
    vertical_line: 'Vertical Line',
    square: 'Square',
    rectangle: 'Reactange',
    cross: 'CrossSign',
    star: 'Star',
    triple_dot_horizontal: 'Triple Dots Horizontal',
    triple_dot_vertical: 'Triple Dots Vertical',
    menu_horizontal: 'Menu Horizontal',
    prpfile: 'Profile',
    mobile: 'Mobile',
    laptop: 'Laptop',
    laptop_with_text: 'Laptop With Text',
    open_in_new_tab: 'Open In New Tab',
    not_allowed: 'Not Allowed',
    focus: 'Focus',
    react: 'React',
    briefcase: 'Briefcase'
  }