import {
    Circle,
    SemiCircle,
    HorizontalLine,
    VerticalLine,
    SolidTriangle,
    Square,
    Reactange,
    CrossSign,
    Star,
    AppsIcon,
    SunSolid,
    SunSolidHorizon,
    ArrowToLeft,
    ArrowToRight,
    ArrowToDown,
    ArrowToUp,
    TripleDotsHorizontal,
    TripleDotsVertical,
    MenuIconHorizontal,
    FileIcon,
    Folder,
    Profile,
    BatteryEmpty,
    BatteryHalfEmpty,
    BatteryFull,
    Mobile,
    Laptop,
    LaptopWithText,
    Building,
    NotAllowed,
    CreditCard,
    DiceOne,
    DiceTwo,
    DiceThree,
    DiceFour,
    DiceFive,
    DiceSix,
    OpenInNewTab,
    WindowsIcon,
    PlusSign,
    MinusSign,
    MultiplySign,
    DivideSign,
    Gmail,
    Instagram,
    Focus,
    ReactIcon,
    BriefCase,
    Globe,
    Moon,
    Correct,
    Wrong,
    SearchIcon,
    ZoomInIcon,
    ZoomOutIcon,
    USB,
    Eye,
    Image,
    Lock,
    LockOpen,
    Dialpad,
    Pokemon,
    Calendar,
    SettingsSlider,
    Mouse,
    Facebook,
    List,
    Marker,
    Youtube,
    Home,
    Camera,
    Stats,
    UserAdd,
    Pause
  } from "./single-element-icons";

  import { TwitterBadge } from "./multi-element-icons/twitterBadge";

export const ComponentsMap = {
    // dark icons
    dice_one: DiceOne,
    dice_two:DiceTwo,
    dice_three:DiceThree,
    dice_four:DiceFour,
    dice_five:DiceFive,
    dice_six:DiceSix,
    apps: AppsIcon,
    sun_solid:SunSolid,
    sun_solid_horizon:SunSolidHorizon,
    arrow_to_left:ArrowToLeft,
    arrow_to_right:ArrowToRight,
    arrow_to_down:ArrowToDown,
    arrow_to_up:ArrowToUp,
    file: FileIcon,
    folder: Folder,
    building: Building,
    credit_card: CreditCard,
    windows: WindowsIcon,
    solid_triangle:SolidTriangle,
    plus: PlusSign,
    minus:MinusSign,
    multiply: MultiplySign,
    divide: DivideSign,
    gmail: Gmail,
    instagram: Instagram,
    facebook: Facebook,
    globe: Globe,
    moon: Moon,
    correct: Correct,
    wrong: Wrong,
    search: SearchIcon,
    zoom_in: ZoomInIcon,
    zoom_out: ZoomOutIcon,
    usb: USB,
    eye: Eye,
    image: Image,
    lock: Lock,
    lock_open: LockOpen,
    dialpad: Dialpad,
    pokemon: Pokemon,
    calendar: Calendar,
    settings_slider: SettingsSlider,
    mouse: Mouse,
    list: List,
    marker: Marker,
    youtube: Youtube,
    home: Home,
    camera: Camera,
    twitter_badge: TwitterBadge,
    stats: Stats,
    pause: Pause,
    // light icons
    battery_full: BatteryFull,
    battery_half_empty:BatteryHalfEmpty,
    battery_empty: BatteryEmpty,
    circle: Circle,
    semi_circle: SemiCircle,
    horizontal_line:HorizontalLine,
    vertical_line: VerticalLine,
    square: Square,
    rectangle: Reactange,
    cross: CrossSign,
    star: Star,
    triple_dot_horizontal: TripleDotsHorizontal,
    triple_dot_vertical: TripleDotsVertical,
    menu_horizontal: MenuIconHorizontal,
    prpfile: Profile,
    mobile: Mobile,
    laptop: Laptop,
    laptop_with_text: LaptopWithText,
    open_in_new_tab: OpenInNewTab,
    not_allowed: NotAllowed,
    focus: Focus,
    react: ReactIcon,
    briefcase: BriefCase,
    userAdd: UserAdd
};

  export const ComponentsList = {
    dice_one: 'Dice One',
    dice_two:'Dice Two',
    dice_three:'Dice Three',
    dice_four:'Dice Four',
    dice_five:'Dice Five',
    dice_six:'Dice Six',
    apps: 'Apps',
    sun_solid:'Sun Solid',
    sun_solid_horizon:'Sun Solid Horizon',
    arrow_to_left:'Arrow Left',
    arrow_to_right:'Arrow Right',
    arrow_to_down:'Arrow Down',
    arrow_to_up:'Arrow Up',
    file: 'File',
    folder: 'Folder',
    building: 'Building',
    credit_card: 'Credit Card',
    windows: 'Windows',
    solid_triangle:'Solid Triangle',
    plus: 'Plus',
    minus:'Minus',
    multiply: 'Multiply',
    divide: 'Divide',
    gmail: 'Gmail',
    instagram: 'Instagram',
    globe: 'Globe',
    moon: 'Moon',
    correct: 'Correct',
    wrong: 'Wrong',
    search: 'Search',
    zoom_in: 'Zoom In',
    zoom_out: 'Zoom Out',
    usb: 'USB',
    eye: 'Eye',
    image: 'Image',
    lock: 'Lock',
    lock_open: 'Lock Open',
    dialpad: 'Dialpad',
    pokemon: 'Pokemon',
    calendar : 'Calendar',
    settings_slider: 'Settings slider',
    mouse: 'Mouse',
    facebook: 'Facebook',
    list: 'List',
    marker: 'Marker',
    youtube: 'Youtube',
    home: 'Home',
    camera: 'Camera',
    twitter_badge: "Twitter Badge",
    stats: 'Stats',
    userAdd: 'User Add',
    pause: 'Pause',
    // light icons
    battery_full: 'Battery Full',
    battery_half_empty:'Battery Half Empty',
    battery_empty: 'Battery Empty',
    circle: 'Circle',
    semi_circle: 'Semi Circle',
    horizontal_line:'Horizontal Line',
    vertical_line: 'Vertical Line',
    square: 'Square',
    rectangle: 'Reactange',
    cross: 'CrossSign',
    star: 'Star',
    triple_dot_horizontal: 'Triple Dots Horizontal',
    triple_dot_vertical: 'Triple Dots Vertical',
    menu_horizontal: 'Menu Horizontal',
    prpfile: 'Profile',
    mobile: 'Mobile',
    laptop: 'Laptop',
    laptop_with_text: 'Laptop With Text',
    open_in_new_tab: 'Open In New Tab',
    not_allowed: 'Not Allowed',
    focus: 'Focus',
    react: 'React',
    briefcase: 'Briefcase'
  }


  export const ComponentObject = [
    {name: 'Dice One', id: 'dice_one', component: DiceOne},
    {name: 'Dice Two', id: 'dice_two', component:DiceTwo},
    {name: 'Dice Three', id: 'dice_three', component: DiceThree},
    {name: 'Dice Four', id:'dice_four', component:DiceFour},
    {name: 'Dice Five', id: 'dice_five', component:DiceFive},
    {name: 'Dice Six', id: 'dice_six', component:DiceSix},
    {name: 'Apps', id:'apps', component: AppsIcon},
    {name: 'Sun Solid', id: 'sun_solid', component:SunSolid},
    {name: 'Sun Solid Horizon', id: 'sun_solid_horizon', component:SunSolidHorizon},
    {name: 'Arrow Left', id: 'arrow_to_left', component:ArrowToLeft},
    {name: 'Arrow Right', id: 'arrow_to_right', component:ArrowToRight},
    {name: 'Arrow Down', id: 'arrow_to_down', component:ArrowToDown},
    {name: 'Arrow Up', id: 'arrow_to_up', component:ArrowToUp},
    {name: 'File', id: 'file', component: FileIcon},
    {name: 'Folder', id:'folder', component: Folder},
    {name: 'Building', id: 'building', component: Building},
    {name: 'Credit Card', id: 'credit_card', component: CreditCard},
    {name: 'Windows', id: 'windows', component: WindowsIcon},
    {name: 'Solid Triangle', id: 'solid_triangle', component:SolidTriangle},
    {name: 'Plus', id: 'plus', component: PlusSign},
    {name: 'Minus', id: 'minus', component:MinusSign},
    {name: 'Multiply', id: 'multiply', component: MultiplySign},
    {name: 'Divide', id: 'divide', component: DivideSign},
    {name: 'Gmail', id: 'gmail', component: Gmail},
    {name: 'Instagram', id: 'instagram', component: Instagram},
    {name: 'Facebook', id: 'facebook', component: Facebook},
    {name: 'Globe', id: 'globe', component: Globe},
    {name: 'Moon', id: 'moon', component: Moon},
    {name: 'Correct', id:'correct', component: Correct},
    {name: 'Wrong', id: 'wrong', component: Wrong},
    {name: 'Search', id: 'search', component: SearchIcon},
    {name: 'Zoom In', id: 'zoom_in', component: ZoomInIcon},
    {name: 'Zoom Out', id: 'zoom_out', component: ZoomOutIcon},
    {name: 'USB', id: 'usb', component: USB},
    {name: 'Eye', id:'eye', component: Eye},
    {name: 'Image', id:'image', component: Image},
    {name: 'Lock', id:'lock', component: Lock},
    {name: 'Lock Open', id:'lock_open', component: LockOpen},
    {name: 'Dialpad', id: 'dialpad', component: Dialpad},
    {name: 'Pokemon', id: 'pokemon', component: Pokemon},
    {name: 'Calendar', id: 'calendar', component: Calendar},
    {name: 'Settings Slider', id: 'settings_slider', component: SettingsSlider},
    {name: 'Mouse', id: 'mouse', component: Mouse},
    {name: 'List', id:'list', component: List},
    {name: 'Marker', id:'marker', component: Marker},
    {name: 'Youtube', id: 'youtube', component: Youtube},
    {name: 'Home', id: 'home', component: Home},
    {name: 'Camera', id: 'camera', component: Camera},
    {name: 'Twitter Badge', id:'twitter_badge', component: TwitterBadge},
    {name: 'Stats', id:'stats', component: Stats},
    {name: 'Pause', id:'pause', component: Pause},
    // light icons
    {name: 'Battery Full', id:'battery_full', component: BatteryFull},
    {name: 'Battery Half', id: 'battery_half_empty', component:BatteryHalfEmpty},
    {name: 'Battery Empty', id:'battery_empty', component: BatteryEmpty},
    {name: 'Circle', id:'circle', component: Circle},
    {name: 'Semi Circle', id: 'semi_circle', component: SemiCircle},
    {name: 'Horizontal Line', id: 'horizontal_line', component:HorizontalLine},
    {name: 'Vertical Line', id:'vertical_line', component: VerticalLine},
    {name: 'Square', id:'square', component: Square},
    {name: 'Rectangle', id:'rectangle', component: Reactange},
    {name: 'Cross', id:'cross', component: CrossSign},
    {name: 'Star', id:'star', component: Star},
    {name: 'Triple Dot Horizontal', id: 'triple_dot_horizontal', component: TripleDotsHorizontal},
    {name: 'Triple Dot Vertical', id:'triple_dot_vertical', component: TripleDotsVertical},
    {name: 'Menu Horizontal', id:'menu_horizontal', component: MenuIconHorizontal},
    {name: 'Profile', id:'prpfile', component: Profile},
    {name: 'Mobile', id:'mobile', component: Mobile},
    {name: 'Laptop', id:'laptop', component: Laptop},
    {name: 'Laptop With Text', id:'laptop_with_text', component: LaptopWithText},
    {name: 'Open In New Tab', id:'open_in_new_tab', component: OpenInNewTab},
    {name: 'Not Allowed', id:'not_allowed', component: NotAllowed},
    {name: 'Focus', id: 'focus', component: Focus},
    {name: 'React', id:'react', component: ReactIcon},
    {name: 'Briefcase', id:'briefcase', component: BriefCase},
    {name: 'User Add', id:'userAdd', component: UserAdd}
  ]